### ISSUE TITLE
Visual artifacts when using drop-down menus on Windows

### ISSUE THREAD

**Issue by vjgalaxy** [processing/processing#4700]
When I try to select anything from the drop-down menus the GUI crashes (the general interface get crazy with things like duplicated menus and strange graphic mess)

Example:
https://cdn.shopify.com/s/files/1/0659/1287/files/2016-10-12_20-18-44.gif

Windows 10 Pro with last update of Java.

**Comment by benfry** [comment]
It's not a Processing bug, but something wrong in Java… Usually this is a problem with graphics drivers, but sometimes we can find a way to avoid triggering the problem.

**Comment by vjgalaxy** [comment]
It is a Quadro M3000. How can I proceed? Thanks.

**Comment by Force098** [comment]
Any ideas on how to proceed? Graphics drivers are updated and no other apps appear to be having issues. Issue occurs with GSync enabled and disabled.

**Comment by vjgalaxy** [comment]
I did not find any solution for the Processing IDE, so I simply installed Eclipse and the Processing Java libraries.

**Comment by windowpane** [comment]
Hi,

I have this same issue on Windows 10.

When I hover over the drop down menus on the top of the GUI, after a while the entire GUI will start displaying incorrectly, see the attached image.

To fix the problem i found that holding down the GUI-screen resize (by holding down the edge of the screen and dragging the the size of the window) for a few seconds makes it go away.


![processing 3 2 3 bug](https://cloud.githubusercontent.com/assets/3112214/21370336/323b99f2-c6d9-11e6-869f-7fd1fd504067.png)

**Comment by adrianrus** [comment]
Might not be related to windows 10, I have the same issue on 7.

**Comment by Lordgoderic** [comment]
I'm also experiencing this problem.
Using Windows 10 64 Bit Home - (Version 1607 - OS Build 14393.693)
Java Version 8 Update 121 (1.8.0_121-b13)
AMD Radeon r9200 - Radeon Driver Version 17.1.1

**Comment by aburstein** [comment]
Having same problem on Windows 7 Pro. [Screencast](http://screencast-o-matic.com/watch/cbn1YV6nYm).
Video card is an AMD Radeon R5 240

**Comment by benfry** [comment]
Added a possible fix in 3.3. Will leave this open until confirmed.

**Comment by Lordgoderic** [comment]
Version 3.3 seems to have solved it on my computer.

Thanks!

**Comment by benfry** [comment]
@Lordgoderic Great, thanks for letting me know

**Comment by benfry** [comment]
Can anyone else confirm that this is fixed?

**Comment by aburstein** [comment]
Just tested, looks like it's resolved the bug! Isn't happening anymore on my system. Will let you know if it returns.

**Comment by benfry** [comment]
Great, thanks.

**Comment by Skyrant** [comment]
This bug is back on windows 7. Please help. All java apps have this same issue.

![image](https://user-images.githubusercontent.com/3149649/46547622-bdeb5400-c8cc-11e8-992f-de5e7ea89723.png)

**Comment by benfry** [comment]
If all Java apps have the issue, then it's not a Processing problem, you're probably having graphics driver issues on your machine.)

(Locking this thread since the original issue was resolved 1.5 years ago)
