### ISSUE TITLE
Could not parse -1 for --display / Could not run the sketch (Target VM failed to initialize) when starting a sketch

### ISSUE THREAD

**Issue by Bennettd77** [processing/processing#5118]
I get the following msg everytime I hit play:

Could not parse -1 for --display
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

I'd like to work with this package but I have no idea what to do with this error.

**Comment by gohai** [comment]
Are you running a 64-bit version of Windows 7? Which version of Processing are you running (there are 32-bit and 64-bit versions of it as well).

What happens when you hit play on an empty sketch?

**Comment by Bennettd77** [comment]
Windows 7 64 bit.
I am using P3 3.3.4 64 bit 
The error I posted was in fact hitting play on an empty sketch.

**Comment by gohai** [comment]
Can you post your `%windir%\system32\drivers\etc\hosts`? Do you have any esoteric firewall or proxy running perhaps?

**Comment by Bennettd77** [comment]
Well I am behind a firewall as I am on a University computer.
I think this is the relevant part of the 'hosts' file you are looking for:
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

**Comment by gohai** [comment]
@Bennettd77

**Comment by GKFX** [comment]
@Bennettd77 Post code like the content of the hosts file between backticks:

    ```
    # code
    ```
gives
```
# code
```
rather than
# code
Anyway, was there a `#` before every line of the snippet of hosts file you posted? That would mean that the code was commented out (i.e. disabled), so it can't be the relevant part. Unless your hosts file is confidential to the university or for any other reason you can't post it,  could you post the whole thing as an attachment?

**Comment by Bennettd77** [comment]
Every line in my host file is like this. Essentially I have nothing in my hosts file.

![capture](https://user-images.githubusercontent.com/7851939/26931788-384d90ce-4c27-11e7-9019-4ad7b83764f9.JPG)

**Comment by BojidarLyutskanov** [comment]
I have the exact same problem on Windows 10 64 bit. I am using the processing 3.3.4 version aswell.

**Comment by BojidarLyutskanov** [comment]
I disabled the firewall but the problem still persists and my hosts.txt file is fully commented

**Comment by FrancisBourre** [comment]
Got the same message displayed in the console when I compile on Mac OSX Sierra from PDE (play button pressed): `Could not parse -1 for --display`

**Comment by deanmalmgren** [comment]
I have the same problem with OSX Sierra using processing 3.3.4. I see `Could not parse -1 for --display`. I can get a trivial example to work, but calls to `size` throw an error that results in no rendering. If there's anything else I can add that would be helpful for debugging, let me know.

**Comment by deanmalmgren** [comment]
quick update. i was able to resolve my problem after looking through the [troubleshooting guide](https://github.com/processing/processing/wiki/Troubleshooting) and moving the files of my sketch to a more standard location. not sure if that will help others on OSX, but I thought I'd mention it.

**Comment by Bennettd77** [comment]
I tried what deanmalmgren suggested and moved a sketch folder somewhere else (the Desktop) and executed from there. Same error with two different sketches.

**Comment by AbhirojPanwar** [comment]
Getting the same error on Windows 8 64-bit.

**Comment by ptr2null** [comment]
Can confirm this on Windows 10 64-bit (latest build). Versions 3.3.2 and 3.3.3 don't have this issue.

**Comment by shah253kt** [comment]
Happened to me as well. Windows 10 x64

**Comment by efroim102** [comment]
I have multiple monitors, to fix the bug and get it to work for now, I went to File -> Preferences and changed the "Run sketched on display:" property to my 2nd monitor which was actually labeled #1 by processing.

I can see a fix was committed 2 days ago but has yet to be released.

**Comment by shah253kt** [comment]
That actually fixed the problem for me. Thanks!

**Comment by Bennettd77** [comment]
I followed efroim102's instructions and was met with the following new error:


Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

**Comment by efroim102** [comment]
@Bennettd77 There's a reported issue (#4853, #4863),  with a Nvidia Driver, If you have a Nvidia Graphics card it might be related.

I personally have a Nvidia GeForce GTX 1060 Graphics card, but changing the monitor selected in preferences fixed it.

**Comment by Swayin** [comment]
i had same error and fix it by moving Processing folder to desktop, but now i don't have this error i still can't run sketch. Here is just empty field when i'm try to run sketch.
![7c4c44ec2b](https://user-images.githubusercontent.com/29628637/27433507-bc9817dc-575d-11e7-8288-df42fb1bfc74.jpg)

**Comment by shivmahesh** [comment]
When I open gcode file in processing following error is on screen .
Error : Unsupported statement 
G4 P150 (waits 150ms)
Iam mahesh joshi here.I am newbie in software,pls help

**Comment by benfry** [comment]
(Locking to prevent confusion/further posts because the issue was resolved almost a year ago)
